version: "3"

volumes: 
        jenkins-data:
                external: true
        jenkins-log:
                external: true

services:
        jenkins:
                image: myjenkins
                container_name: myjenkins
                ports:
                        - "8080:8080"
                        - "50000:50000"
                volumes:
                        - jenkins-data:/var/jenkins_home
                        - jenkins-log:/var/log/jenkins
                        # adds access to docker daemon for jenkins docker agents
                        - /var/run/docker.sock:/var/run/docker.sock
                networks:
                        - net

networks:
        net: