version: "3"

volumes: 
        jenkins-data:
                external: true
        jenkins-log:
                external: true

services:
        jenkins:
                image: myjenkins
                container_name: myjenkins
                ports:
                        - "8080:8080"
                volumes:
                        - jenkins-data:/var/jenkins_home
                        - jenkins-log:/var/log/jenkins
                networks:
                        - net

networks:
        net: