version: "3"
services:
        jenkins:
                image: jenkins/jenkins
                container_name: jenkins
                ports:
                        - "8080:8080"
                volumes:
                        - ${JENKINS_DATA_VOLUME}:/var/jenkins_home
                        - ${JENKINS_LOG_VOLUME}:/var/log/jenkins
                networks:
                        - net
networks:
        net: 