version: "3"

volumes: 
        jenkins-data:
                external: true
        jenkins-logs:
                external: true

services:
        jenkins:
                build:
                        context: ./
                image: myjenkins
                container_name: myjenkins
                ports:
                        - "${HOST_WEB_UI_PORT}:8080"
                        - "${HOST_API_PORT}:50000"
                volumes:
                        - jenkins-data:/var/jenkins_home
                        - jenkins-logs:/var/log/jenkins
                        # adds access to docker daemon for jenkins docker agents
                        - /var/run/docker.sock:/var/run/docker.sock