apiVersion: apps/v1
kind: Deployment 
metadata:
  name: traffic-app-deployment
  labels:
    app: web-portfolio
    tier: back-end
spec:
  template: 
    metadata:
      name: traffic-app-pod
      labels:
        app: web-portfolio
        tier: back-end
    spec:
      containers:
        - name: hello-world
          image: hello-world
  replicas: 2  
  selector: 
    matchLabels:
      app: web-portfolio
      tier: back-end