apiVersion: v1
kind: Service
metadata: 
  name: api-svc
  namespace: default
  labels:
    app: api-app
spec:
  type: NodePort
  selector:
    app: api-app
  ports:
    - name: http
      protocol: TCP
      port:  8080
      targetPort: 8080
      nodePort: 30069