apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-agents-pv
  namespace: cloudbees-core
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Mi