def modifiedImages = []

pipeline {
    agent none

    environment {
        APPS = "frontend-app,traffic-app"
        DIR = ""
    }

    options{
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }    

    stages {

        stage('determine modified apps'){
            agent{
                label 'master'
            }
            steps{
                script{
                    // modifiedImages = getModifiedApps(APPS)
                    modifiedImages = ["testimage1", "testimage2"]
                    modifiedImages.each{ print it }
                }
            }
        }

        stage('build and push docker images') {
            agent {
                label "kubernetes-agent"
            }
            options{
                skipDefaultCheckout()
            }
            steps{
                script{
                    DIR = sh (
                        script: 'pwd',
                        returnStdout: true
                    ).trim()
                }
                sh 'mkdir .kube'
                sh 'ls -la'
                withCredentials([file(credentialsId: 'kubernetes', variable: 'kubeconfig')]){
                    sh "echo $KUBECONFIG"
                    sh "cp \$kubeconfig .kube/config"
                    sh 'ls .kube/'
                    sh 'cat .kube/config'
                    sh "export KUBECONFIG=${DIR}/.kube/config"
                }
                sh "kubectl rollout restart deployment -n default frontend-dep"
            }
        }
        
    }

    post {
        always{
            echo "all done"
        }
    }
    
}
