apiVersion: apps/v1
kind: Deployment 
metadata:
  name: frontend-deployment
  labels:
    app: web-portfolio
    tier: front-end
spec:
  template: 
    metadata:
      name: angular-pod
      labels:
        app: web-portfolio
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
  replicas: 1  
  selector: 
    matchLabels:
      app: web-portfolio
      tier: front-end