apiVersion: v1
kind: Service
metadata: 
  name: traffic-app-node-port-service
  labels:
    app: traffic-app
    tier: back-end
spec:
  type: NodePort
  # this is a list, we can forward to many ports
  ports:
    # the port our target pod is listening on
    - targetPort: 80
      # the port we are going to forward to
      port: 80
      # the port our Nodeport service is listening on
      nodePort: 30008
  # used to identify which subset of pods listening on our target port to forward to
  selector:
    app: traffic-app
    tier: back-end