apiVersion: v1
kind: Service
metadata: 
  name: traffic-app-load-balancer
  labels:
    app: traffic-app
    tier: back-end
spec:
  type: LoadBalancer
  selector:
    app: traffic-app
    tier: back-end
  ports:
    - nodePort: 31000
      port: 80
      targetPort: 80