apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-03-22T15:58:44Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: traefik
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-9.17.5
  name: traefik
  namespace: default
  resourceVersion: "17391"
  uid: 7a465f24-8f34-4b0f-8d83-3d3cbf2c570f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: traefik
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: traefik
        helm.sh/chart: traefik-9.17.5
    spec:
      containers:
      - args:
        - --global.checknewversion
        - --global.sendanonymoususage
        - --entryPoints.traefik.address=:9000/tcp
        - --entryPoints.web.address=:8000/tcp
        - --entryPoints.websecure.address=:8443/tcp
        - --api.dashboard=true
        - --api.insecure
        - --ping=true
        - --providers.kubernetescrd
        - --providers.kubernetesingress
        image: traefik:2.4.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 9000
          name: traefik
         protocol: TCP                
        - containerPort: 8000              
          name: web                              
          protocol: TCP                      
        - containerPort: 8443                      
          name: websecure                  
          protocol: TCP                    
        readinessProbe:                    
          failureThreshold: 1          
          httpGet:                         
            path: /ping                          
            port: 9000                       
            scheme: HTTP                           
          initialDelaySeconds: 10
          periodSeconds: 10              
          successThreshold: 1              
          timeoutSeconds: 2                
        resources: {}                      
        securityContext:                         
          capabilities:                      
            drop:                                  
            - ALL             
          readOnlyRootFilesystem: true   
          runAsGroup: 65532              
          runAsNonRoot: true          
          runAsUser: 65532                 
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File       
        volumeMounts:                               
        - mountPath: /data            
          name: data         
        - mountPath: /tmp    
          name: tmp                   
      dnsPolicy: ClusterFirst              
      nodeSelector:                              
        web-server: "true"                   
      restartPolicy: Always                         
      schedulerName: default-scheduler
      securityContext:       
        fsGroup: 65532                
      serviceAccount: traefik      
      serviceAccountName: traefik      
      terminationGracePeriodSeconds: 60          
      volumes:                                   
      - emptyDir: {}                               
        name: data                                 
      - emptyDir: {}          
        name: tmp                     
status:                               
  availableReplicas: 1                 
  conditions:                          
  - lastTransitionTime: "2021-03-22T15:58:44Z"
    lastUpdateTime: "2021-03-22T15:58:44Z"          
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable      
    status: "True"                               
    type: Available                   
  - lastTransitionTime: "2021-03-22T16:09:32Z"
    lastUpdateTime: "2021-03-22T17:18:16Z"
    message: ReplicaSet "traefik-dd467cbdd" has successfully progressed.
    reason: NewReplicaSetAvailable                  
    status: "True"                                                      
    type: Progressing                     
  observedGeneration: 3                          
  readyReplicas: 1                    
  replicas: 1                
  updatedReplicas: 1