apiVersion: v1
kind: Service
metadata:
  name: neural-network-svc
  namespace: default
  labels:
    app: neural-network-app
spec:
  selector:
    app: neural-network-app
  ports:
    - name: http
      protocol: TCP
      port:  80
      targetPort: 80