
pipeline {
    agent none

    options{
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }

    triggers {
        GenericTrigger(
            genericVariables: [
                [key: 'image', value: '$.push_data.tag']
            ],

            token: 'kubernetes_update',
            causeString: 'Triggered on $image',

            printContributedVariables: true,
            printPostContent: true,

            silentResponse: false
        )
  }    

    stages {

        stage('update kubernetes deployment') {
            agent {
                label "kubernetes-agent"
            }
            environment{
                KUBECONFIG = credentials('remote-kubeconfig')
            }
            options{
                skipDefaultCheckout()
            }
            steps{
                script{
                    println("image to be updated: ${image}")
                    updateDeployment(image)
                }
            }
        }
        
    }
    
}

////////////////////////////////////////////////////////////////////////////////////
// Groovy Scripts
////////////////////////////////////////////////////////////////////////////////////

def updateDeployment(image){
    println("updating deployment for image: ${image}")
    tokens = image.split('-')
    deployment = token[0] + '-dep'
    print "deployment name: " + deployment
    
    // sh"kubectl --kubeconfig ${KUBECONFIG} get deployments.apps"
}